{ config, pkgs, lib, ... }:

{

services.hyprpaper = {
	enable = true;
	settings = {
		preload = ["/home/nekonix/wallpapers/1839888782432317856-0.jpg"];
		wallpaper = [",/home/nekonix/wallpapers/1839888782432317856-0.jpg"];
	};
};


wayland.windowManager.hyprland = {
  enable = true;
  settings = {

    ########################################################################################
    #AUTOGENERATED HYPR CONFIG.
    #PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
    #OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
    ########################################################################################

    #
    # Please note not all available settings / options are set here.
    # For a full list, see the wiki
    #

    # autogenerated = 1;  # remove this line to remove the warning

    # See https://wiki.hyprland.org/Configuring/Monitors/
    monitor = [
      "eDP-1,     1920x1080@144, 0x0,     1"
      "HDMI-A-1,  1920x1080@144, -1920x0, 1"
      #"        ,  preferred    , -1920x0, 1"
      #",preferred,auto,1, mirror, eDP-1"
    ];

    # Variables de entorno env
    env = [
      "WLR_NO_HARDWARE_CURSORS,1"
      #"XCURSOR_SIZE,24"
      #"XCURSOR_THEME,Bibata-Modern-Ice"
      "QT_QPA_PLATFORMTHEME,qt5ct"
      "XDG_CURRENT_DESKTOP,Hyprland"
      "GTK_THEME,Adwaita:dark"
      "QT_STYLE_OVERRIDE,Breeze"
      "QT_QPA_PLATFORM,wayland"

      # Estos de abajo son sólo para cuando
      # tengas GPU Nvidia
      #"LIBVA_DRIVER_NAME,nvidia"
      #"__GLX_VENDOR_LIBRARY_NAME,nvidia"
    ];


    # Execute your favorite apps at launch
    exec-once = [
        "waybar & dunst & spotify & obsidian & thunderbird & qbittorrent"
        "systemctl --user enable opentabletdriver.service --now"
        #"/home/nekonix/config-nix/scripts/refresco.sh"
        "systemctl --user start hyprpolkitagent"

	"/home/nekonix/config-nix/scripts/alertaBateria.sh"
	"/home/nekonix/config-nix/scripts/estadoBateria.sh"
	"/home/nekonix/config-nix/scripts/temperaturaCpu.sh"
	"sudo /home/nekonix/config-nix/scripts/ventiladores.sh"
        #"/nix/store/$(ls -la /nix/store | grep polkit-kde-agent | grep '^d' | awk '{print $9}' | head -n 1)/libexec/polkit-kde-authentication-agent-1"
      ];

      workspace = [
        "special:spotify, on-created-empty: spotify"
        "special:obsidian, on-created-empty: obsidian"
        "special:mail, on-created-empty: thunderbird"
        #"special:discord, on-created-empty: discord"
        "1, monitor:HDMI-A-1, default:true, on-created-empty: firefox"
	"12, monitor:eDP-1, default:false, on-created-empty: qbittorrent"
        "11, monitor:eDP-1, default:true, on-created-empty: /home/nekonix/config-nix/scripts/adornosTerminal.sh"
      ];

      "$terminal" = "kitty";
      "$fileManager" = "thunar";
      "$menu" = "rofi -show drun -show-icons";
      # See https://wiki.hyprland.org/Configuring/Keywords/ for more
      "$mainMod" = "SUPER";


      # For all categories, see https://wiki.hyprland.org/Configuring/Variables/
      input = {
        kb_layout = "latam";
        numlock_by_default = true;
        follow_mouse = 1;

        touchpad = {
          natural_scroll = "yes";
          scroll_factor = 0.25;
        };

        sensitivity = -0.5;
      };

      general = {
        # See https://wiki.hyprland.org/Configuring/Variables/ for more
        gaps_in = 2;
        gaps_out = 2;
        border_size = 1;
        "col.active_border" = "rgba(8b9efdee) rgba(5cbcd6ee) 45deg";
        "col.inactive_border" = "rgba(595959aa)";
        layout = "dwindle";

        # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false;
      };

      decoration = {
        # See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 10;
        blur = {
          enabled = false;
          size = 3;
          passes = 1;
        };
        drop_shadow = "yes";
        shadow_range = 4;
        shadow_render_power = 3;
        "col.shadow" = "rgba(1a1a1aee)";
      };

      animations = {
        enabled = "yes";
        # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

        bezier = "myBezier, 0.05, 0.9, 0.1, 1.05";
        animation = [
          "windows, 1, 7, myBezier"
          "windowsOut, 1, 7, default, popin 80%"
          "border, 1, 10, default"
          "borderangle, 1, 8, default"
          "fade, 1, 7, default"
          "workspaces, 1, 6, default"
        ];
      };

      dwindle = {
        # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        pseudotile = "yes";
        preserve_split = "yes";
      };

      master = {
        # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        new_is_master = true;
      };

      gestures = {
        # See https://wiki.hyprland.org/Configuring/Variables/ for more
        workspace_swipe = true;
        workspace_swipe_fingers = 3;
      };

      misc = {
        force_default_wallpaper = ",/home/nekonix/wallpapers/Kath.png";
        disable_hyprland_logo = true;
      };

      # Example per-device config
      # See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
      #"device:epic-mouse-v1" = {
      #  sensitivity = -0.5;
      #};



      # Example windowrule v1
      # windowrule = float, ^(kitty)$
      # Example windowrule v2
      # windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
      # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
      #windowrulev2 = ["nomaximizerequest, class:.*"];
      windowrulev2 = [
      		"workspace special:spotify silent, class:^(Spotify)$"
		"workspace special:obsidian silent, class:^(obsidian)$"
		"workspace special:mail silent, class:^(thunderbird)$"
		#"workspace 11 silent, class:^(kitty)$, title:^(cmatrix)$"
		#"workspace 11 silent, title:^(asciiquarium)$"
		"workspace 12 silent, class:^(org.qbittorrent.qBittorrent)$"
	];


      # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
      bind = [
        "$mainMod, Q, exec, $terminal"
        "$mainMod, W, killactive,"
        "$mainMod, M, exit,"
        "$mainMod, E, exec, $fileManager"
        "$mainMod, R, exec, $menu"
        "$mainMod, P, exec, ~/config-nix/scripts/mostrarFondo.sh"
        "$mainMod, S, togglesplit"
        "$mainMod, L, exec, ~/config-nix/scripts/bloqueoPantalla.sh"
        "$mainMod, O, exec, ~/config-nix/scripts/menuRofi.sh"
	
        "$mainMod, F, fullscreen"
	"$mainMod, period, exec, ~/config-nix/scripts/emojis.sh"

        # Cambiar la ventana con focus
        "$mainMod, left, movefocus, l"
        #"$mainMod, J, movefocus, l"
        "$mainMod, right, movefocus, r"
        #"$mainMod, L, movefocus, r"
        "$mainMod, up, movefocus, u"
        #"$mainMod, I, movefocus, u"
        "$mainMod, down, movefocus, d"
        #"$mainMod, K, movefocus, d"

        # Ir al workspace selecionado
        "$mainMod, 1, workspace, 1"
        "$mainMod, 2, workspace, 2"
        "$mainMod, 3, workspace, 3"
        "$mainMod, 4, workspace, 4"
        "$mainMod, 5, workspace, 5"
        "$mainMod, 6, workspace, 6"
        "$mainMod, 7, workspace, 7"
        "$mainMod, 8, workspace, 8"
        "$mainMod, 9, workspace, 9"
        "$mainMod, 0, workspace, 10"

        "$mainMod, F1, workspace, 11"
        "$mainMod, F2, workspace, 12"
        "$mainMod, F3, workspace, 13"
        "$mainMod, F4, workspace, 14"
        "$mainMod, F5, workspace, 15"
        "$mainMod, F6, workspace, 16"
        "$mainMod, F7, workspace, 17"
        "$mainMod, F8, workspace, 18"
        "$mainMod, F9, workspace, 19"
        "$mainMod, F10, workspace, 20"

        # Mover la ventana con focus al workspace seleccionado
        "$mainMod SHIFT, 1, movetoworkspace, 1"
        "$mainMod SHIFT, 2, movetoworkspace, 2"
        "$mainMod SHIFT, 3, movetoworkspace, 3"
        "$mainMod SHIFT, 4, movetoworkspace, 4"
        "$mainMod SHIFT, 5, movetoworkspace, 5"
        "$mainMod SHIFT, 6, movetoworkspace, 6"
        "$mainMod SHIFT, 7, movetoworkspace, 7"
        "$mainMod SHIFT, 8, movetoworkspace, 8"
        "$mainMod SHIFT, 9, movetoworkspace, 9"
        "$mainMod SHIFT, 0, movetoworkspace, 10"

        "$mainMod SHIFT, F1, movetoworkspace, 11"
        "$mainMod SHIFT, F2, movetoworkspace, 12"
        "$mainMod SHIFT, F3, movetoworkspace, 13"
        "$mainMod SHIFT, F4, movetoworkspace, 14"
        "$mainMod SHIFT, F5, movetoworkspace, 15"
        "$mainMod SHIFT, F6, movetoworkspace, 16"
        "$mainMod SHIFT, F7, movetoworkspace, 17"
        "$mainMod SHIFT, F8, movetoworkspace, 18"
        "$mainMod SHIFT, F9, movetoworkspace, 19"
        "$mainMod SHIFT, F10, movetoworkspace, 20"

        # Workspaces especiales
        "$mainMod, Z, togglespecialworkspace, spotify"
        "$mainMod SHIFT, Z, movetoworkspace, special:spotify"
        "$mainMod, X, togglespecialworkspace, obsidian"
        "$mainMod SHIFT, X, movetoworkspace, special:obsidian"
        "$mainMod, C, togglespecialworkspace, mail"
        "$mainMod SHIFT, C, movetoworkspace, special:mail"
        "$mainMod, V, togglespecialworkspace, discord"
        "$mainMod SHIFT, V, movetoworkspace, special:discord"


        # Moverse entre workspaces. Rueda ratón y con teclas A, D
        "$mainMod, mouse_down, workspace, e-1"
        "$mainMod, mouse_up, workspace, e+1"
        "$mainMod, A, workspace, e-1"
	",mouse:275, workspace, e+1"
	",mouse:276, workspace, e-1"
        "$mainMod, D, workspace, e+1"
        
        # Control de media
        ", XF86AudioPlay, exec, playerctl play-pause"
        ", XF86AudioNext, exec, playerctl next"
        ", XF86AudioPrev, exec, playerctl previous"
        ", XF86AudioStop, exec, playerctl stop"

        # Pantallazos
        ", Print, exec, grim -g \"$(slurp -d)\""
      ];

      # Los bindm son cuando se usan los botones del mouse
      # mouse:272 es click izquierdo
      # mouse:273 es click derecho
      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizewindow"
      ];


      # Los binde son cuando puedes dejar presionada la tecla
      # y seguirá ejecutando el comando
      binde = [
        # Controles de volumen
        #", XF86audioraisevolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +1% && dunstify -r 91190 -u low \"Volumen +\" \"$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}')\""
        #", XF86audiolowervolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -1% && dunstify -r 91190 -u low \"Volumen -\" \"$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}')\""
        #", XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle && dunstify -r 91190 -u low \"Silenciado\" \"$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')\""
        

        ", XF86AudioRaiseVolume, exec, ~/config-nix/scripts/volumen.sh up"
        ", XF86AudioLowerVolume, exec, ~/config-nix/scripts/volumen.sh down"
        ", XF86AudioMute, exec, ~/config-nix/scripts/volumen.sh mute"

        # MUTE
        #", XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle && MUTE=\$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print \$2}') && MSG=\$( [ \"\$MUTE\" = \"yes\" ] && echo \"🔇 Silenciado\" || echo \"🔊 Activado\") && dunstify -r 91190 -u low \"Mute\" \"\$MSG\""



        # Controles de brillo
        ", XF86MonBrightnessUp, exec, brightnessctl set 5%+"
        ", XF86MonBrightnessDown, exec, brightnessctl set 5%-"
      ];

      debug = {
        suppress_errors = true;
      };







  };

};









}
