{ config, pkgs, lib, ... }:

{
  #programs.home-manager.enable = true;

  users.users.nekonix = {
    isNormalUser = true;
    home = "/home/nekonix";
  };



  home-manager = {
    backupFileExtension = "backup";
    useGlobalPkgs = true;
    useUserPackages = true;
    users.nekonix = { pkgs, ... }: {
      home.stateVersion = "24.11"; # Ajusta según la versión de NixOS
      home.file = {
      ".config/hypr/hyprland.conf".text = ''
        # /home/nekoArch/.config/hypr/hyprland.conf
        ########################################################################################
        #AUTOGENERATED HYPR CONFIG.
        #PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
        #OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
        ########################################################################################

        #
        # Please note not all available settings / options are set here.
        # For a full list, see the wiki
        #

        #autogenerated = 1 # remove this line to remove the warning

        # See https://wiki.hyprland.org/Configuring/Monitors/
        monitor=eDP-1,1920x1080@144, 0x0, 1
        #monitor=,preferred,auto,1, mirror, eDP-1
        #monitor= HDMI-A-1, 1920x1080@144, up, 1
        monitor = , preferred, 0x-1080, 1
        env = WLR_NO_HARDWARE_CURSORS,1

        # Dispatchers


        # See https://wiki.hyprland.org/Configuring/Keywords/ for more

        # Execute your favorite apps at launch
        exec-once = waybar & firefox & hyprpaper & dunst
        exec-once = /nix/store/$(ls -la /nix/store | grep polkit-kde-agent | grep '^d' | awk '{print $9}' | head -n 1)/libexec/polkit-kde-authentication-agent-1
        exec-once = systemctl --user enable opentabletdriver.service --now
        exec-once = /home/nekonix/config-nix/refresco.sh


        # Source a file (multi-file configs)
        # source = ~/.config/hypr/myColors.conf

        # Set programs that you use
        $terminal = kitty
        $fileManager = thunar
        $menu = rofi -show drun -show-icons

        # Some default env vars.
        env = XCURSOR_SIZE,24
        env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that

        # For all categories, see https://wiki.hyprland.org/Configuring/Variables/
        input {
            kb_layout = latam
            kb_variant =
            kb_model =
            kb_options =
            kb_rules =
            numlock_by_default = true
            follow_mouse = 1

            touchpad {
                natural_scroll = yes
                scroll_factor = 0.25
            }



            sensitivity = -0.5 # -1.0 - 1.0, 0 means no modification.
        }

        general {
            # See https://wiki.hyprland.org/Configuring/Variables/ for more

            gaps_in = 2
            gaps_out = 2
            border_size = 1
            col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
            col.inactive_border = rgba(595959aa)

            layout = dwindle

            # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
            allow_tearing = false
        }

        decoration {
            # See https://wiki.hyprland.org/Configuring/Variables/ for more

            rounding = 10
            
            blur {
                enabled = false
                size = 3
                passes = 1
            }

            drop_shadow = yes
            shadow_range = 4
            shadow_render_power = 3
            col.shadow = rgba(1a1a1aee)
        }

        animations {
            enabled = yes

            # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

            bezier = myBezier, 0.05, 0.9, 0.1, 1.05

            animation = windows, 1, 7, myBezier
            animation = windowsOut, 1, 7, default, popin 80%
            animation = border, 1, 10, default
            animation = borderangle, 1, 8, default
            animation = fade, 1, 7, default
            animation = workspaces, 1, 6, default
        }

        dwindle {
            # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
            pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
            preserve_split = yes # you probably want this
        }

        master {
            # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
            new_is_master = true
        }

        gestures {
            # See https://wiki.hyprland.org/Configuring/Variables/ for more
            workspace_swipe = true
            workspace_swipe_fingers = 3
        
        }

        misc { 
            force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
            disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
        }

        # Example per-device config
        # See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
        device:epic-mouse-v1 {
            sensitivity = -0.5
        }



        # Example windowrule v1
        # windowrule = float, ^(kitty)$
        # Example windowrule v2
        # windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
        # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
        windowrulev2 = nomaximizerequest, class:.* # You'll probably like this.


        # See https://wiki.hyprland.org/Configuring/Keywords/ for more
        $mainMod = SUPER

        # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
        bind = $mainMod, Q, exec, $terminal
        bind = $mainMod, W, killactive, 
        bind = $mainMod, M, exit, 
        bind = $mainMod, E, exec, $fileManager
        bind = $mainMod, V, togglefloating, 
        bind = $mainMod, R, exec, $menu
        bind = $mainMod, P, pseudo, # dwindle
        bind = $mainMod, S, togglesplit, # dwindle
        bind = $mainMod, L, exec, swaylock

        # Move focus with mainMod + arrow keys
        bind = $mainMod, left, movefocus, l
        bind = $mainMod, right, movefocus, r
        bind = $mainMod, up, movefocus, u
        bind = $mainMod, down, movefocus, d

        # Switch workspaces with mainMod + [0-9]
        bind = $mainMod, 1, workspace, 1
        bind = $mainMod, 2, workspace, 2
        bind = $mainMod, 3, workspace, 3
        bind = $mainMod, 4, workspace, 4
        bind = $mainMod, 5, workspace, 5
        bind = $mainMod, 6, workspace, 6
        bind = $mainMod, 7, workspace, 7
        bind = $mainMod, 8, workspace, 8
        bind = $mainMod, 9, workspace, 9
        bind = $mainMod, 0, workspace, 10

        # Move active window to a workspace with mainMod + SHIFT + [0-9]
        bind = $mainMod SHIFT, 1, movetoworkspace, 1
        bind = $mainMod SHIFT, 2, movetoworkspace, 2
        bind = $mainMod SHIFT, 3, movetoworkspace, 3
        bind = $mainMod SHIFT, 4, movetoworkspace, 4
        bind = $mainMod SHIFT, 5, movetoworkspace, 5
        bind = $mainMod SHIFT, 6, movetoworkspace, 6
        bind = $mainMod SHIFT, 7, movetoworkspace, 7
        bind = $mainMod SHIFT, 8, movetoworkspace, 8
        bind = $mainMod SHIFT, 9, movetoworkspace, 9
        bind = $mainMod SHIFT, 0, movetoworkspace, 10

        # Example special workspace (scratchpad)
        #bind = $mainMod, S, togglespecialworkspace, magic
        #bind = $mainMod SHIFT, S, movetoworkspace, special:magic

        # Scroll through existing workspaces with mainMod + scroll
        bind = $mainMod, mouse_down, workspace, e-1
        bind = $mainMod, mouse_up, workspace, e+1
        bind = $mainMod, A, workspace, e-1
        bind = $mainMod, D, workspace, e+1

        # Move/resize windows with mainMod + LMB/RMB and dragging
        bindm = $mainMod, mouse:272, movewindow
        bindm = $mainMod, mouse:273, resizewindow

        # Hacer la pantalla completa de una cosa
        bind = $mainMod, F, fullscreen

        # Volume and Media


        binde= , XF86audioraisevolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
        binde= , XF86audiolowervolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
        binde= , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle 
        binde= , XF86MonBrightnessUp, exec, brightnessctl set 5%+
        binde= , XF86MonBrightnessDown, exec, brightnessctl set 5%-
        bind =, Print, exec, grim -g "$(slurp -d)"

        debug {
            suppress_errors = true 
        }
      '';
      ".config/hypr/hyprpaper.conf".text = ''
        preload = /home/nekonix/Kath.png
        preload = /home/nekonix/ThingsWeLike/GoldCan6955/Goldcan-1845630265236021630-0.jpg
        wallpaper = ,/home/nekonix/Kath.png
        #wallpaper = ,/home/nekonix/ThingsWeLike/GoldCan6955/Goldcan-1845630265236021630-0.jpg
      '';
      };

     
      wayland.windowManager.hyprland.systemd.variables = ["--all"];

    };

      
  };
  
}
